config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "instagram_callback" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "articles#index"
  resources :articles, only: [:show, :index] do 
    resources :comments, only: [:create, :destroy]
  end
  resources :subscriptions, only: [:create, :show] do 
    delete ":id" => "subscriptions#destroy", on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  after_create :send_notification

  mount_uploader :cover, ImageUploader

  has_many :comments

  scope :recent, -> {order(updated_at: :desc).limit(3)}

private
  def send_notification
    Subscription.delay.newsletter(self.id)
  end

end

app/models/article_sweeper.rb
class ArticleSweeper < ActionController::Caching::Sweeper
  observe Article

  def after_save(article)
    expire_fragment "footer/recent_articles"
    expire_fragment "show/recent_articles"
    expire_cache article
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article, touch: true
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  include Tokenable
  validates :email, uniqueness: true, email: true

  def self.newsletter(article_id)
    all.each do |sub|
      ArticleMailer.delay.new_article(email: sub.email, token: sub.token, article: article_id)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :trackable, :omniauthable, :omniauth_providers => [:instagram]

  mount_uploader :avatar, ImageUploader

  has_many :comments


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.nickname   # assuming the user model has a name
      user.remote_avatar_url = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order(updated_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.friendly.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :back }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if @comment.user == current_user
      @comment.destroy
    end
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment].permit(:content, :article_id)
    end
end

app/controllers/instagram_callback_controller.rb
class InstagramCallbackController < Devise::OmniauthCallbacksController

  def instagram
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Instagram") if is_navigational_format?
    end
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :destroy]

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end


  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to :back, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :back }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find_by(token: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params[:subscription].permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def markdown(text)
    options = {:hard_wrap => true,
               :filter_html => true,
               :autolink => true, 
               :no_intra_emphasis => true, 
               :fenced_code => true, 
               :fenced_code_blocks => true,
               :gh_blockcode => true,
               :tables => true}
    engine = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    engine.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/articles/index.html.erb
<section id="hero" class="light-typo">
  <div id="cover-image" class="image-bg animated fadeIn"></div>
  <div class="container welcome-content">
    <div class="middle-text">
      <h1>Hello there, my name is Ivan</h1>
      <h2>This theme was honestly purchased</h2>
      <a class="btn smooth-scroll" href="#start">Let's Go</a>
    </div>
  </div>
</section>

<div id="start" class="container content">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% @articles.each do |article| %>
        <% cache article do %> 
          <article class="clearfix">
            <div class="post-date">
              <%= article.updated_at.strftime("%B %d, %Y")%><span><a href=""><%= pluralize(article.comments.count, 'comment') %></a></span>
            </div>    
            <h2><%= link_to article.title, article %></h2>
            <p>
              <%= markdown article.content[0..300] %>
              <%= link_to "Read more", article %>
            </p>
          </article>
        <% end %>
      <% end %>
    </div>  
  </div><!-- end row -->
</div>

app/views/articles/show.html.erb
<section id="hero" class="light-typo">
  <div id="cover-image" class="animated fadeIn" style="background-image: url('<%=@article.cover.url%>');"></div>
  <div class="container welcome-content">
    <div class="middle-text">
      <h1><%=@article.title %></h1>
    </div>
  </div>
</section>

<div class="container content">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="post-date">
        <%=@article.created_at.strftime("%B %d, %Y") %><span><a href=""><%= pluralize(@article.comments.count, 'comment') %></a></span>
      </div>    

      <% cache do %>  
        <p>
          <%= markdown @article.content %>
        </p>  
      <% end %>
      

      <ul class="social-links outline text-center">
        <li><a href="#link"><i class="icon-twitter"></i></a></li>
        <li><a href="#link"><i class="icon-facebook"></i></a></li>
        <li><a href="#link"><i class="icon-googleplus"></i></a></li>
      </ul>

      <% cache "show/recent_articles" do %>
        <div class="post-popular">
          <div class="row hidden-xs">
            <% Article.recent.each do |article| %>
              <% cache article do %>
                <div class="col-sm-4 col-md-4"> 
                  <%= link_to image_tag(article.cover.url, class: "img-responsive"), article %>
                  <h4 class="text-center"><%= link_to article.title, article %></h4>
                  <p class="post-date text-center"><%= article.updated_at.strftime("%B %d, %Y")%></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>

      <%= render "comments/list" %>
      <%= render "comments/form" %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <h3>Add a new comment</h3>
  <%= form_for @article.comments.build, url: article_comments_path(@article), class:"myform" do |f| %>
    <%= f.hidden_field :article_id %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 wow fadeInUp" >
        <div class="form-group">
          <div class="controls">
            <%= f.text_area :content, class: "form-control input-lg requiredField", 
                                     placeholder: "Join the discussion...", 
                                     rows: 3, 
                                     data: {error_empty: "Please enter comment"} %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <%= f.submit "Send Comment", class: "btn btn-block", 
                                       data: { error_message: "Error!",
                                               sending_message: "Sending...",
                                               ok_message: "Comment Sent"
                                              } %>

          <input type="hidden" name="submitted" id="submitted3" value="true">
        </div>  
      </div>  
    </div>  
  <% end %>
<% else %>
  <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <%=link_to "Login via Instagram", user_omniauth_authorize_path(:instagram), class:"btn btn-block" %>
        </div>  
      </div>  
    </div>  
<% end %>

app/views/comments/_list.html.erb
<h3><%= pluralize(@article.comments.count, 'comment') %> </h3>  
<% @article.comments.joins(:user).each do |comment| %>
  <% cache comment do %>
    <div class="media">
      <hr>
      <a class="pull-left avatar" href="#">
        <%=image_tag comment.user.avatar.url, size: "40x40", class: "media-object img-circle"%>
      </a>
      <div class="media-body">
        <h4 class="media-heading">
          <a href=""><%= comment.user.name %></a>
          <span><%=comment.created_at.strftime("%T") %></span>
        </h4>
        <p><%= comment.content %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Key Lime</title>
    <meta charset="utf-8">
    <meta name="description" content="Key Lime Responsive HTML5/CSS3 Template from angelostudio.net">
    <meta name="author" content="ANGELOSTUDIO.NET">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Merriweather:400,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="img/ico/32.png" sizes="32x32" type="image/png"/>
    <link rel="apple-touch-icon-precomposed" href="img/ico/60.png" type="image/png"/>
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/ico/72.png" type="image/png"/>
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="img/ico/120.png" type="image/png"/>
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="img/ico/152.png" type="image/png"/>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="home">
    <div id="wrap">
      <div id="main-nav" class="">
        <div class="container">
          <div class="nav-header">
              <a class="nav-brand" href="/"><i class="icon-lime"></i>Key Lime</a>
              <a class="btn btn-blog outline-white pull-right" href="#" data-toggle="modal" data-target="#loginModal">Subscribe</a>
            </div>
        </div>
      </div>
      <% if flash[:notice] %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>    

    <div class="modal fade login" id="loginModal" aria-hidden="true">
        <div class="modal-dialog login">
          <div class="modal-content">
           <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Subscribe to this blog</h4>
          </div>
          <div class="modal-body">  
            <div class="box">
              <div class="form loginBox">
                <%= form_for(Subscription.new, class: "myform") do |f| %>
                  <div class="form-group">
                    <div class="controls">
                      <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
                    </div>
                  </div>
                  <%= f.submit "Submit", class: "btn btn-block" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <div class="forgot login-footer">
            </div>
          </div>        
          </div>
        </div>
      </div>
    <%= javascript_include_tag 'application'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="container">
      <div class="row">
        <%= render "shared/statistics" %>
        <%= render "shared/recent_articles" %>
        <div class="col-sm-4 col-md-4 footer-widget clearfix">
          <h3>Contacts</h3>
          <ul class="tags">
            <li><a href="mailto:status.enable@gmail.com">e-mail</a></li>
            <li><a href="http://facebook.com/shamatov">Facebook</a></li>
            <li><a href="http://linkedin.com/in/shamatov">Linked In</a></li>
            <li><a href="http://stackoverflow.com/users/703725/ivan-shamatov">Stackoverflow</a></li>
            <li><a href="https://github.com/IvanShamatov">Github</a></li>
            <li><a href="http://bitbucket.org/IvanShamatov">BitBucket</a></li>                         
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">
    <div class="container">
      <p class="pull-left">Designed by <a href="http://angelostudio.net">Angelo Studio.</a></p>
    </div>
  </div>
</footer>

app/views/shared/_recent_articles.html.erb
<% cache "footer/recent_articles" do %>
  <div class="col-sm-4 col-md-4 footer-widget">
    <h3>Recent posts</h3>
    <div class="post-recent-widget">
      <div class="row">
        <div class="col-sm-12">
          <% Article.recent.each do |article| %>
            <% cache article do  %>
              <div class="media">
                <%=link_to image_tag(article.cover.url, width: "80", class: "media-object"), article, class: "pull-left" %>
                <div class="media-body">
                  <h4 class="media-heading"><%= link_to article.title, article %>
                  <p class="post-date"><%= article.created_at.strftime("%B %d, %Y") %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_statistics.html.erb
<% cache do %>
  <div class="col-sm-4 col-md-4 footer-widget">
    <h3>Statistics</h3>

    <div class="stats">
      <div class="line">
        <span class="counter"><%=Article.count%></span>
        <span class="caption">Articles</span>
      </div>
      <div class="line">
        <span class="counter"><%=Comment.count%></span>
        <span class="caption">Comments</span>
      </div>
      <div class="line">
        <span class="counter"><%=User.count%></span>
        <span class="caption">Users</span>
      </div>                    
    </div>
  </div>
<% end %>

app/views/subscriptions/_form.html.erb
<%= form_for(Subscription.new) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>E-mail:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Back', articles_path %>
<%= link_to "Unsubscribe", subscription_path(@subscription.token), method: :delete, confirm: "Are you sure you want to unsubscribe?" %>